name: RSSNewsBook
main: com.esperia09.rssnewsbook.RSSNewsBookPlugin
version: 0.0.1
author: neske
commands:
  rssnews:
    description: Convert Written book to RSS News book
    usage: /rssnews after hold "Written book" in your's main hand.
